# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](../assets/numpy_vs_python_list.png)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [1]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

NumPy Vectorized Multiplication (my_arr * 2):
322 μs ± 4.45 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
25.4 ms ± 624 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](../assets/numpy_ndarray.png)

In [2]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [3]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### [EXERCISE 1: Creation & Casting]
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [4]:
# Your code here
import numpy as np

# 1. Create a 3x4 array of all ones
ones_array = np.ones((3, 4))
print("Original array of ones:\n", ones_array)

# 2. Cast this array to float32
ones_array_float32 = ones_array.astype(np.float32)
print("\nArray of ones cast to float32:\n", ones_array_float32)
print("Dtype of float32 array:", ones_array_float32.dtype)

# 3. Create an array of strings representing numbers
string_array = np.array(['1.25', '-9.6', '42'])
print("\nOriginal string array:\n", string_array)

# 4. Cast it to float
float_array = string_array.astype(float)
print("\nString array cast to float:\n", float_array)
print("Dtype of float array:", float_array.dtype)

Original array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of ones cast to float32:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Dtype of float32 array: float32

Original string array:
 ['1.25' '-9.6' '42']

String array cast to float:
 [ 1.25 -9.6  42.  ]
Dtype of float array: float64


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](../assets/vectorization.png)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [2]:
# [DEMO] Arithmetic & Broadcasting
import numpy   as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax. 

### 2D Array Indexing Syntax
![2d_array_indexing](../assets/ndarray_axis_index.png)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [3]:
# [DEMO] Slicing views
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])

Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]

First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### [EXERCISE 2: The Logic of Slicing]
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [4]:
# Your code here
# Assuming arr2d is already defined from the previous DEMO cell
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1. Select the first column of arr2d using a slice.
first_column = arr2d[:, 0]
print("First column of arr2d:\n", first_column)

# 2. Set all values in the second row to 0.
print("\nOriginal arr2d before modifying second row:\n", arr2d)
arr2d[1, :] = 0 # Or arr2d[1] = 0
print("arr2d after setting second row to 0:\n", arr2d)

# Socratic Prompt: How does arr2d[1] differ from arr2d[1, :]? (Hint: check shapes)
# Let's inspect their shapes:
print("\nShape of arr2d[1]:", arr2d[1].shape)
print("Shape of arr2d[1, :]:", arr2d[1, :].shape)

First column of arr2d:
 [1 4 7]

Original arr2d before modifying second row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d after setting second row to 0:
 [[1 2 3]
 [0 0 0]
 [7 8 9]]

Shape of arr2d[1]: (3,)
Shape of arr2d[1, :]: (3,)


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [5]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


### [EXERCISE 3: Complex Filtering]
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [ ]:
# Your code here
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names != 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

bob_or_will_mask = (names == 'Bob') | (names == 'Will')

scores[scores<80]=0
print("Scores with values less than 80 set to 0:\n", scores)      


Mask: [ True False  True  True  True False False]
Bob's scores:
 [[ 75  80]
 [ 95 100]
 [100  77]
 [ 85  92]]
Scores with values less than 80 set to 0:
 [[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays. 

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [11]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

Random Array:
 [[ 1.25492434e-01 -3.49831468e-01 -9.81954179e-01  7.71705006e-01]
 [-4.01401804e-01 -3.16861813e-04  1.06615640e+00  8.90085377e-01]
 [ 2.31737567e-01  2.13515387e+00 -4.06310028e-01  2.71367567e-02]]

Mean down rows (axis=0): [-0.01472393  0.59500185 -0.10736927  0.56297571]
Sum across columns (axis=1): [-0.43458821  1.55452311  1.98771816]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](../assets/matrix_multiplication.png)

In [12]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### [EXERCISE 4: Reshaping & Statistics]
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [13]:
# Your code here
# 1. Create an array of 15 integers using arange(15) and reshape it to (3, 5).
arr = np.arange(15).reshape((3, 5))
print("Original reshaped array:\n", arr)

# 2. Calculate the average value of each row.
row_averages = arr.mean(axis=1)
print("\nAverage value of each row:\n", row_averages)

# 3. Use np.unique() to find distinct elements in an array of your choice.
# Let's use the 'arr' created above for this.
unique_elements = np.unique(arr)
print("\nDistinct elements in the array:\n", unique_elements)

# 4. Transpose the reshaped array using .T and check the new shape.
transposed_arr = arr.T
print("\nTransposed array:\n", transposed_arr)
print("Shape of transposed array:", transposed_arr.shape)

Original reshaped array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Average value of each row:
 [ 2.  7. 12.]

Distinct elements in the array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Transposed array:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
Shape of transposed array: (5, 3)
